### ISSUE TITLE
Expose configuration options

### ISSUE THREAD

**Issue by Ramblurr** [null-null-null/ember-lokijs#1]
I'd like to use ember-lokijs with different LokiJS storage adapters (namely: https://github.com/cosmith/loki-cordova-fs-adapter). However there is no way to pass config options to ember-loki.

Ideally the ["new Loki"]](https://github.com/null-null-null/ember-lokijs/blob/a5e4f0716e2a863de061ba98418f62056891d8d4/addon/adapters/ember-lokijs/lokijs.js#L19) would pass some externalized config options.

**Comment by briarsweetbriar** [comment]
Just made a new commit. Let me know if it works for you! You can find documentation on it [here](https://github.com/null-null-null/ember-lokijs#adapter).

**Comment by Ramblurr** [comment]
That looks great, thanks for the quick reply! My only additional request would be the ability to pass in the various options to the db. See http://lokijs.org/#/docs#db

In particular the ones I need are `autosave` and `autosaveInterval`.

**Comment by briarsweetbriar** [comment]
That seems like a better pattern for specifying the adapter, as well. You can find the new docs [here](https://github.com/null-null-null/ember-lokijs#lokioptions). Let me know if that works!

Also, I checked out your site. It's always good to see engineers applying their skills to causes they believe in. Best of luck, @Ramblurr!
